# Generated by Django 4.0.6 on 2022-07-29 21:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
